# Generated by Django 4.2 on 2023-04-07 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('mediaId', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('comments', models.IntegerField()),
                ('engajament', models.IntegerField(null=True)),
                ('likes', models.IntegerField()),
                ('plays', models.IntegerField(null=True)),
                ('shares', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('reach', models.IntegerField(null=True)),
                ('impressions', models.IntegerField(null=True)),
                ('link', models.URLField()),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('ALBUM', 'Album'), ('IMAGE', 'Image')], max_length=10)),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateTimeField(null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('pageId', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('followers', models.IntegerField()),
                ('totalPosts', models.IntegerField(blank=True, null=True)),
                ('profileViews', models.IntegerField(blank=True, null=True)),
                ('siteClicks', models.IntegerField(null=True)),
                ('profileImpressions', models.IntegerField(blank=True, null=True)),
                ('profileReach', models.IntegerField(blank=True, null=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.profile')),
            ],
        ),
    ]
